# Generated by Django 4.1.7 on 2023-02-21 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSubscriber', models.PositiveIntegerField()),
                ('pseudo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSubscription', models.PositiveIntegerField()),
                ('pseudo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idComment', models.PositiveIntegerField()),
                ('contenu', models.TextField(max_length=1000)),
                ('likes', models.PositiveBigIntegerField()),
                ('sendTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPost', models.PositiveIntegerField()),
                ('contenu', models.TextField(max_length=1500)),
                ('lienExterne', models.ImageField(upload_to='')),
                ('idRecipient', models.PositiveBigIntegerField()),
                ('sendTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPost', models.PositiveIntegerField()),
                ('contenu', models.TextField(max_length=1500)),
                ('image', models.ImageField(upload_to='')),
                ('likes', models.PositiveBigIntegerField()),
                ('comments', models.PositiveBigIntegerField()),
                ('sendTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=26)),
                ('prenom', models.CharField(max_length=26)),
                ('mail', models.EmailField(max_length=254)),
                ('mdp', models.CharField(max_length=100)),
                ('dateInscription', models.DateTimeField()),
                ('dateNaissance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSubscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.abonnement')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSubscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.abonne')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.user')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.message')),
                ('idRecipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.user')),
            ],
        ),
        migrations.CreateModel(
            name='landinge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=40)),
                ('pdp', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=300)),
                ('abonnements', models.PositiveBigIntegerField()),
                ('abonnes', models.PositiveBigIntegerField()),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.commentaire')),
                ('idPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.user'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='idAuteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.user'),
        ),
    ]
