# Generated by Django 4.1.7 on 2023-02-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='landinge',
            new_name='Profile',
        ),
    ]
