# Generated by Django 4.1.7 on 2023-02-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_rename_landinge_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='idAuteur',
        ),
        migrations.RemoveField(
            model_name='message',
            name='idUser',
        ),
        migrations.RemoveField(
            model_name='post',
            name='idUser',
        ),
        migrations.RemoveField(
            model_name='post_comment',
            name='idComment',
        ),
        migrations.RemoveField(
            model_name='post_comment',
            name='idPost',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='idUser',
        ),
        migrations.RemoveField(
            model_name='recipient_message',
            name='idMessage',
        ),
        migrations.RemoveField(
            model_name='recipient_message',
            name='idRecipient',
        ),
        migrations.RemoveField(
            model_name='user_subscriber',
            name='idSubscriber',
        ),
        migrations.RemoveField(
            model_name='user_subscriber',
            name='idUser',
        ),
        migrations.RemoveField(
            model_name='user_subscription',
            name='idSubscription',
        ),
        migrations.RemoveField(
            model_name='user_subscription',
            name='idUser',
        ),
        migrations.DeleteModel(
            name='Abonne',
        ),
        migrations.DeleteModel(
            name='Abonnement',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Post_Comment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Recipient_Message',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User_Subscriber',
        ),
        migrations.DeleteModel(
            name='User_Subscription',
        ),
    ]
