# Generated by Django 4.1.7 on 2023-02-24 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sendingTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
